#__Task-1: find the base image for nodejs 


ENV APP_PORT=5000
WORKDIR /app
COPY package.json /app
RUN npm install
# __Ta-sk-2: copy code to container at /app


# __Task-3: Set Expose port
EXPOSE 
CMD ["npm", "start"]
