# INSTRUCTION arguments

# FROM <image>:<tag>
FROM ubuntu:latest

## install python
# RUN <command>
RUN apt update && apt install -y python3

## copy files to container
# COPY <src> <dest>
COPY hello.py /hello.py

## set working directory
# WORKDIR <path>
WORKDIR /

## set environment variable
# ENV <key> <value>
ENV COMPUTERNAME ubuntu-container
ENV HOSTNAME ubuntu-container

## run command
# CMD <command>
CMD ["python3", "hello.py"]