# INSTRUCTION arguments

## Select base image
# FROM <image>:<tag>


## install python
# RUN <command>


## copy files to container
# COPY <src> <dest>


## set environment variable
# ENV <key> <value>
ENV COMPUTERNAME ubuntu-container
ENV HOSTNAME ubuntu-container

## set working directory
# WORKDIR <path>
WORKDIR /

## run command
# CMD <command>
